{% set version = "0.8.0.dev" %}

package:
  name: geopandas
  version: {{ version }}

source:
  git_url: https://github.com/geopandas/geopandas.git
  git_branch: master

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pandas >=0.23
    - shapely
    - fiona
    - pyproj >=2.2.0
    - rtree

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: 'LICENSE.txt'
  summary: 'Geographic pandas extensions'

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
